version: "3"
services:
  nodejs:
    container_name: "nodejs"
    build:
      context: .
      dockerfile: DocherFile
    ports:
      - "3001:3001"
  pg:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"